@baseUrl = http://inmytime.me/api
@contentType = application/json

POST {{baseUrl}}/polls
Content-Type: {{contentType}}

{
  "title": "Weekly Team Meeting",
  "description": "Please indicate your available times.",
  "ownerId": "user_uuid_12345",
  "config": {
    "targetDates": [
      "2025-11-25T00:00:00.000Z",
      "2025-11-26T00:00:00.000Z"
    ],
    "dailyStartTime": "09:00",
    "dailyEndTime": "17:00",
    "slotDuration": 30
  },
  "availableDates": [
    "2025-11-25T09:00:00.000Z",
    "2025-11-25T09:30:00.000Z",
    "2025-11-26T10:00:00.000Z"
  ]
}

###

@pollId = 69209b6a2b1728c76bf88487
GET {{baseUrl}}/poll/{{pollId}}

###

PATCH {{baseUrl}}/poll/{{pollId}}
Content-Type: {{contentType}}

{
  "action": "vote",
  "voteData": {
    "tempVoterId": "browser_fingerprint_999",
    "voterName": "Ahmet",
    "voterColor": "#3498db",
    "selectedSlots": [
      "2025-11-25T09:00:00.000Z",
      "2025-11-25T09:30:00.000Z"
    ]
  }
}

###

PATCH {{baseUrl}}/poll/{{pollId}}
Content-Type: {{contentType}}

{
  "action": "finalize",
  "status": "finalized",
  "finalTime": "2025-11-25T09:30:00.000Z"
}